
name: "Create Release Draft"

on:
  push:
    tags: v*

jobs:
  Release:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 100
    - uses: fregante/release-with-changelog@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        exclude: '^skipci:'
        commit-template: '- {title} ([{hash}]({url}))'
        draft: true
